// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwhjhtmyivksibgtyuks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3aGpodG15aXZrc2liZ3R5dWtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2MDY3MzksImV4cCI6MjA1MjE4MjczOX0.-TSMMZGT_tS8xDS6O33cCB-GbaqpmXOL2e5NQA_Ayq8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);